### ISSUE TITLE
Support Subject Alternative Name in Cerficate generation (CSR)

### ISSUE THREAD

**Issue by scop** [scop/portecle#22]
Google Chrome requires a Subject Alternative Name in self signed certificates. Common Name is not used anymore.

See https://www.thesslstore.com/blog/security-changes-in-chrome-58/

Currently there's no field in Portecle to fill in this field when generating a KeyPair ...

Reported by: nicovn

**Comment by picpicpic** [comment]
Hi,
In the version 1.11,
it's working fine for a single dns alternative name but I can't enter multiple alternative dns which could be pretty useful :)

Thx and regards
Aldric

**Comment by scop** [comment]
Sure, and it would also be useful to have something other than just DNS SAN's there. But that deserves a new issue of its own ;) (This one's implemented as requested.)
