### ISSUE TITLE
Creating a jks container for Jira

### ISSUE THREAD

**Issue by elev8or** [scop/portecle#52]
Hi,
i created a jks container and imported a .CRT certificate.
after saving and implementing the jks container in Jira the Jira system gives following error message out:
Serve: Failed to initialize end point protection associated with ProtocolHandler 
java.io.IOException: Alias Wildcard does not identify a key entry.
I have a Key File for the .Crt certificate.
Where can i import the keyhole with portecle or how can i implement the ssl certificate with protocol in Jira?

Best
Mike

**Comment by scop** [comment]
If I understand correctly, you should import the certificate into the same keystore where your key already is. But this does not seem to be an issue with Portecle itself, so closing.

**Comment by elev8or** [comment]
Hi Scop,
I can import the certificate, but the necessary key file can't be imported.
How can I import the key file?
I have no option to import the key file.
Best
Mike

**Comment by scop** [comment]
Tools -> import key pair
