### ISSUE TITLE
Dumb newbie question ... runs on JRE?

### ISSUE THREAD

**Issue by mwoffenden** [scop/portecle#54]
Will Portecle (Windows) run with just a JRE installed?

**Comment by mwoffenden** [comment]
Anyone????

**Comment by scop** [comment]
It should. Why not just try it out?

**Comment by mwoffenden** [comment]
Good point!  Once I set JAVA_HOME it worked great.

**Comment by scop** [comment]
BTW, runtime environment was already mentioned in README.md. Maybe the above commit makes it more clear.

**Comment by mwoffenden** [comment]
That helps, but my confusion was over terminology, which newbies like me did not understand.  

So I created this little cheat sheet which might help others.

Java SE (Java Platform, Standard Edition) refers to any/all of the following:

- JRE (Java Runtime Environment) - Is for the end user running Java on a desktop. Covers most end-users needs. Contains everything required to run Java applications on your system.
- JDK (Java SE Development Kit) - Is for Software Developers. For Java Developers. Includes a complete JRE plus tools for developing, debugging, and monitoring Java applications.
- Server JRE (Server Java Runtime Environment) - Is for Administrators running applications on a server. For deploying Java applications on servers. Includes tools for JVM monitoring and tools commonly required for server applications, but does not include browser integration (the Java plug-in), auto-update, nor an installer.
